### ISSUE TITLE
Error code 104: ngrok is not yet ready to start tunnels

### ISSUE THREAD

**Issue by Rainymood** [twitterdev/autohook#20]
Getting a 104 error when trying to run the out of the box example. 

### Expected behavior

```JS
$ node index.js
Getting webhooks…
Removing webhooks…
Removing https//.../webhook
Registering https://.../webhook as a new webhook…
Webhook created.
Subscribed to ... activities.
```
### Actual behavior

```JS
$ node index.js
Getting webhooks…
Removing webhooks…
{
  error_code: 104,
  status_code: 503,
  msg: 'ngrok is not yet ready to start tunnels',
  details: {
    err: 'a successful ngrok tunnel session has not yet been established'
  }
}
```

### Steps to reproduce the behavior

`index.js`

```JS
require('dotenv').config()
const { Autohook } = require('twitter-autohook');

async function initWebhook(oauth_token, oauth_token_secret) {
    try {
        const webhook = new Autohook();

        // Removes existing webhooks
        await webhook.removeWebhooks();

        // Listens to incoming activity
        webhook.on("event", event => console.log("Something happened:", event));

        // Starts a server and adds a new webhook
        await webhook.start();

        // Subscribes to a user's activity
        await webhook.subscribe({ oauth_token, oauth_token_secret });
    } catch (e) {
        console.log(e);
    }
}

initWebhook(
    process.env.TWITTER_ACCESS_TOKEN,
    process.env.TWITTER_ACCESS_TOKEN_SECRET
);
```

`.env`

```
TWITTER_CONSUMER_KEY= ...
TWITTER_CONSUMER_SECRET= ...
TWITTER_ACCESS_TOKEN= ...
TWITTER_ACCESS_TOKEN_SECRET= ...
TWITTER_WEBHOOK_ENV=...
```

`package.json`

```JS
...
  "dependencies": {
    "dotenv": "^8.2.0",
    "twitter": "^1.7.1",
    "twitter-autohook": "^1.4.2"
  }
...
```

**Comment by Rainymood** [comment]
I suspect this is a firewall issue. Running this from a network *not* behind a firewall I get the following (error): 

```
$ node index.js
Getting webhooks…
Removing webhooks…
Registering https://d65ab0ba.ngrok.io/webhook as a new webhook…
WebhookURIError: Non-200 response code during CRC GET request (i.e. 404, 500, etc). (HTTP status: 400, Twitter code: 214)
    at setWebhook (/Users/jan/Documents/Projects/ultra/node_modules/twitter-autohook/index.js:188:12)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Autohook.start (/Users/jan/Documents/Projects/ultra/node_modules/twitter-autohook/index.js:289:23)
    at async initWebhook (/Users/jan/Documents/Projects/ultra/autohook.js:16:9) {
  name: 'WebhookURIError',
  code: 214
}
```

**Comment by iamdaniele** [comment]
Thanks for clarifying @Rainymood. I'm going to close this out for now. Please feel free to comment if you still need help, so we can reopen.
