### ISSUE TITLE
AuthenticationError: Client application is not permitted to access this user's webhook subscriptions

### ISSUE THREAD

**Issue by epilith** [twitterdev/autohook#24]
I am trying to setup a simple webhook, but I am unable to subscribe. I am using the sample index.js file and have double checked that all the tokens are present and correct in my .env.twitter file.

The output I get is:
```Getting webhooks…
Removing webhooks…
Removing https://b57d939c.ngrok.io/webhook…
Registering https://6e55eae0.ngrok.io/webhook as a new webhook…
Webhook created.
{ AuthenticationError: Client application is not permitted to access this user's webhook subscriptions. (HTTP status: 401, Twitter code: 348)
    at tryError (/Users/ethomas/Documents/cocktail-bot/node_modules/twitter-autohook/errors/index.js:53:12)
    at Autohook.subscribe (/Users/ethomas/Documents/cocktail-bot/node_modules/twitter-autohook/index.js:285:19)
    at process._tickCallback (internal/process/next_tick.js:68:7) name: 'AuthenticationError', code: 348 }```

**Comment by yordis** [comment]
@epilith hey there,

Do you remember how you fix this issue?
