### ISSUE TITLE
`.start()` => "AuthenticationError: High latency on CRC GET request." 

### ISSUE THREAD

**Issue by thiskevinwang** [twitterdev/autohook#30]
I'm trying to run code inside a Docker Container, on a Raspberry Pi.

### Expected behavior

My code that runs on a **Raspberry Pi 4 Model B** itself, should run Docker container on the Pi

- ✅ successful logs output
```bash
pi@raspberrypi ~/r/k-bot> npm run dev

> k-bot@1.0.0 dev /home/pi/repos/k-bot
> ts-node-dev --no-notify --respawn --transpileOnly ./src

Using ts-node version 8.10.1, typescript version 4.0.0-dev.20200512
Getting webhooks…
Removing webhooks…
Removing https://941591d6.ngrok.io/webhook…
__removed
Registering https://b0138eb2.ngrok.io/webhook as a new webhook…
Webhook created.
__started
Subscribed to thekevinwang's activities.
__subscribed
```

### Actual behavior

When running the same code **inside a Docker container**, something is throwing an error when I call the Autohook instance's `.start()` method.

- ❌ error logs output
```bash
pi@raspberrypi ~/r/k-bot> docker run --rm -it my-app

> k-bot@1.0.0 dev /usr/src/app
> ts-node-dev --no-notify --respawn --transpileOnly ./src

Using ts-node version 8.10.1, typescript version 4.0.0-dev.20200514
Getting webhooks…
Removing webhooks…
__removed
Registering https://e6af4d6e.ngrok.io/webhook as a new webhook…
$$$ AuthenticationError: High latency on CRC GET request. Your webhook should respond in less than 3 seconds. (HTTP status: 400, Twitter code: 214)
    at tryError (/usr/src/app/node_modules/twitter-autohook/errors/index.js:53:12)
    at Autohook.setWebhook (/usr/src/app/node_modules/twitter-autohook/index.js:205:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at Autohook.start (/usr/src/app/node_modules/twitter-autohook/index.js:270:7) {
  code: 214
}
{ name: 'AuthenticationError', code: 214 }
```

### Steps to reproduce the behavior

Clone Repo
```bash
git clone https://github.com/thiskevinwang/k-bot.git
cd k-bot
```

Need the 4 different twitter keys in a `.env`
```bash
touch .env
```
- example ts/js usage / env va names
    ```
    // this is TS/JS
    token: process.env.APP_ACCESS_TOKEN,
    token_secret: process.env.APP_ACCESS_TOKEN_SECRET,
    consumer_key: process.env.API_KEY,
    consumer_secret: process.env.API_SECRET_KEY,
    ```

Build Docker Image

```bash
docker build --rm -t my-app .
```

Run Docker Container
```
docker run --rm -it my-app
```

See error 😞

**Comment by thiskevinwang** [comment]
This code 
✅runs on my laptop
✅runs in Docker, on my laptop
✅runs on my Raspberry Pi 4
❌does not run in Docker, on my Raspberry Pi 4
