### ISSUE TITLE
'token' is empty or not set. Check your configuration and try again.

### ISSUE THREAD

**Issue by Jaagrav** [twitterdev/autohook#44]
'token' is empty or not set. Check your configuration and try again.

### Expected behavior

To output what's written on this [article](https://developer.twitter.com/en/docs/twitter-api/premium/account-activity-api/guides/twitter-account-activity-tutorial-autohook) by Twitter Developers
```
$ node index.js
Getting webhooks…
Removing webhooks…
Removing https://ce085a0d.ngrok.io/webhook…
Registering https://e3fd0ff6.ngrok.io/webhook as a new webhook…
Webhook created.
Subscribed to <username>'s activities.
```

### Actual behavior

```
$ npm start

> codex-bot@1.0.0 start D:\Jaagrav's Stuff\Coding\NodeJS Projex\supcoder
> node src/index

TypeError: 'token' is empty or not set. Check your configuration and try again.
    at D:\Jaagrav's Stuff\Coding\NodeJS Projex\supcoder\node_modules\twitter-autohook\index.js:131:15
    at Array.map (<anonymous>)
    at new Autohook (D:\Jaagrav's Stuff\Coding\NodeJS Projex\supcoder\node_modules\twitter-autohook\index.js:128:85)
    at D:\Jaagrav's Stuff\Coding\NodeJS Projex\supcoder\src\index.js:5:21
    at Object.<anonymous> (D:\Jaagrav's Stuff\Coding\NodeJS Projex\supcoder\src\index.js:23:3)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! codex-bot@1.0.0 start: `node src/index`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the codex-bot@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Jaagrav\AppData\Roaming\npm-cache\_logs\2021-02-16T15_43_25_427Z-debug.log
```

### Steps to reproduce the behavior
This is the exact code I have written after following the article,
```javascript
const { Autohook } = require("twitter-autohook");

(async (start) => {
  try {
    const webhook = new Autohook();

    // Removes existing webhooks
    await webhook.removeWebhooks();

    // Starts a server and adds a new webhook
    await webhook.start();

    // Subscribes to your own user's activity
    await webhook.subscribe({
      oauth_token: process.env.TWITTER_ACCESS_TOKEN,
      oauth_token_secret: process.env.TWITTER_ACCESS_TOKEN_SECRET,
    });
  } catch (e) {
    // Display the error and quit
    console.error(e);
    process.exit(1);
  }
})();
```

**Comment by Jaagrav** [comment]
To the future viewers of this issue, in order to resolve this issue, you can simply refer to the [examples](https://github.com/twitterdev/autohook/blob/master/examples/listen.js), the code written there worked for me on the first attempt. You can both listen for new message events and send messages with the help of the [example](https://github.com/twitterdev/autohook/blob/master/examples/listen.js), it's actually not that hard to set up.

**Comment by AlexandruMares** [comment]
1) create .env
TWITTER_CONSUMER_KEY= **your API key**
TWITTER_CONSUMER_SECRET= **your API secret**
TWITTER_ACCESS_TOKEN= **your token**
TWITTER_ACCESS_TOKEN_SECRET= **your token secret**
TWITTER_WEBHOOK_ENV= **create activity environment https://developer.twitter.com/en/account/environments**

2) require('dotenv').config() at the start of your file
