### ISSUE TITLE
Freezing during installation

### ISSUE THREAD

**Issue by sajibsrs** [twitterdev/autohook#53]
Installation freezes when trying to install using 'npm i -g twitter-autohook'

Freezing happens on following line: 
`(##################) ⠴ reify:ngrok: timing reifyNode:node_modules/twitter-autohook/node_modules/lodash Completed in 393ms`

After force stopping with 'ctrl+c' terminal shows these:

```
npm ERR! path /home/user/.nvm/versions/node/v18.12.1/lib/node_modules/twitter-autohook/node_modules/ngrok
npm ERR! command failed
npm ERR! signal SIGINT
npm ERR! command sh -c -- node ./postinstall.js
npm ERR! ngrok - cached download found at /home/user/.ngrok/aHR0cHM6Ly9iaW4uZXF1aW5veC5pby9jLzRWbUR6QTdpYUhiL25ncm9rLXN0YWJsZS1saW51eC1hbWQ2NC56aXA=.zip
npm ERR! ngrok - unpacking binary
npm ERR! ngrok - downloading binary https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
ngrok - downloading progress: 4011224/13832437
npm ERR! ngrok - error unpacking binary Error: Could not find the End of Central Directory Record
npm ERR!     at DecompressZip.findEndOfDirectory (/home/user/.nvm/versions/node/v18.12.1/lib/node_modules/twitter-autohook/node_modules/decompress-zip/lib/decompress-zip.js:176:15)
npm ERR!     at _fulfilled (/home/user/.nvm/versions/node/v18.12.1/lib/node_modules/twitter-autohook/node_modules/q/q.js:854:54)
npm ERR!     at /home/user/.nvm/versions/node/v18.12.1/lib/node_modules/twitter-autohook/node_modules/q/q.js:883:30
npm ERR!     at Promise.promise.promiseDispatch (/home/user/.nvm/versions/node/v18.12.1/lib/node_modules/twitter-autohook/node_modules/q/q.js:816:13)
npm ERR!     at /home/user/.nvm/versions/node/v18.12.1/lib/node_modules/twitter-autohook/node_modules/q/q.js:624:44
npm ERR!     at runSingle (/home/user/.nvm/versions/node/v18.12.1/lib/node_modules/twitter-autohook/node_modules/q/q.js:137:13)
npm ERR!     at flush (/home/user/.nvm/versions/node/v18.12.1/lib/node_modules/twitter-autohook/node_modules/q/q.js:125:13)
npm ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
npm ERR! ngrok - install failed, retrying

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2022-12-29T13_01_25_615Z-debug-0.log
```

**Comment by sajibsrs** [comment]
Problem was download from 'https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip' was too slow. I had to use VPN and set location to US Central to get it working.
